# site settings

title: PORTFOLIO

subtitle: by JESSE HONG

email: jjhong89@gmail.com

description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.

baseurl:  # the subpath of your site, e.g. /blog

url: "" # the base hostname & protocol for your site

author:

street_address: 

city: 

state: 

zip_code:

country: 

phone: 



# homepage tiles

tiles-source: posts # accepts "posts" or "pages"

tiles-count: 200



# social settings

500px_url:

facebook_url:

github_url:

gitlab_url: 

googleplus_url: 

instagram_url:

linkedin_url: 

pinterest_url:

slack_url:

twitter_url:



# build settings

markdown: kramdown



sass:

  style: compressed

